"""Change relo_headers to JSONB

Revision ID: 98724d857609
Revises: bc829a1545ce
Create Date: 2024-09-02 11:54:44.915259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98724d857609'
down_revision: Union[str, None] = 'bc829a1545ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_request_log_relo_id', table_name='request_log')
    op.drop_index('ix_request_log_relo_method', table_name='request_log')
    op.drop_index('ix_request_log_relo_url', table_name='request_log')
    op.drop_table('request_log')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_log',
    sa.Column('relo_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('relo_method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('relo_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('relo_headers', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('relo_body', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('relo_status_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('relo_ip_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('relo_device_info', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('relo_absolute_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('relo_request_duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('relo_response_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('relo_timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('relo_id', name='request_log_pkey')
    )
    op.create_index('ix_request_log_relo_url', 'request_log', ['relo_url'], unique=False)
    op.create_index('ix_request_log_relo_method', 'request_log', ['relo_method'], unique=False)
    op.create_index('ix_request_log_relo_id', 'request_log', ['relo_id'], unique=False)
    # ### end Alembic commands ###
