"""Change relo_headers to JSONB

Revision ID: 04036d07ba0b
Revises: 98724d857609
Create Date: 2024-09-02 11:55:23.587143

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '04036d07ba0b'
down_revision: Union[str, None] = '98724d857609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
